FROM ubuntu:24.04

RUN apt-get update -qq && DEBIAN_FRONTEND="noninteractive" apt-get install -qq \
  git \
  wget \
  python3 \
  python3-venv \
  tar \
  p7zip-full \
  cmake \
  software-properties-common \
  build-essential \
  curl zip unzip tar \  
  pkg-config \
  autoconf \
  cmake \
  ninja-build \
  flex \
  bison \
  libgsasl7 \
  libkrb5-3 \
  && apt-get clean -qq

RUN wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
RUN tar xzf Python-2.7.18.tgz
RUN cd Python-2.7.18 && ./configure --enable-optimizations && make altinstall
RUN ln -s "/usr/local/bin/python2.7" "/usr/bin/python2"

RUN rm -f /usr/bin/g++
RUN apt-get install -y g++-11
RUN ln -s /usr/bin/g++-11 /usr/bin/g++
RUN g++ --version

RUN apt-get install -y libc-client-dev libkrb5-dev
RUN apt-get install -y libc-client-dev libgsasl7-dev
RUN apt-get install -y libc-client-dev uuid-dev

ADD ./entrypoint-build.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
